// Generated by CoffeeScript 1.6.1
var context;

context = (function() {

  function context(ctx) {
    this.ctx = ctx;
  }

  context.prototype.get = function(path) {
    var data, name, nextname, parts;
    parts = path.split('.');
    name = parts.shift();
    data = this.ctx[name];
    while (parts.length && (data != null)) {
      nextname = parts.shift();
      data = data[nextname];
      if (data != null) {
        name = nextname;
      }
    }
    return data || '';
  };

  context.prototype.has = function(path) {
    return this.get(path) && this.get(path) !== '';
  };

  return context;

})();

if (typeof module !== "undefined" && module !== null) {
  module.exports = context;
} else {
  this.context = context;
}
